version: '3.7'

volumes:
  db-data:
  logs-data:
  bundler-data:

services:
  mycel-api:
    build: .
    command: bundle exec ruby api_server.rb -sv -e development -p 9000
    volumes:
      - .:/app
      - logs-data:/app/logs
      - bundler-data:/usr/local/bundle
    environment:
      USERNAME: ${MYCEL_USERNAME:-mycel}
      PASSWORD: ${MYCEL_PASSWORD:-secret}
      SIP_HOST: ${MYCEL_SIP_HOST:-siphost}
      SIP_PORT: ${MYCEL_SIP_PORT:-999}
      SIP_USER: ${MYCEL_SIP_USER:-sipuser}
      SIP_PASS: ${MYCEL_SIP_PASS:-sippass}
    ports:
      - "9000:9000"
    depends_on:
      - mycel-db

  mycel-server:
    build: .
    command: bundle exec ruby server.rb -sv -e development -p 9001
    volumes:
      - .:/app
      - logs-data:/app/logs
      - bundler-data:/usr/local/bundle
    environment:
      USERNAME: ${MYCEL_USERNAME:-mycel}
      PASSWORD: ${MYCEL_PASSWORD:-secret}
      SIP_HOST: ${MYCEL_SIP_HOST:-siphost}
      SIP_PORT: ${MYCEL_SIP_PORT:-999}
      SIP_USER: ${MYCEL_SIP_USER:-sipuser}
      SIP_PASS: ${MYCEL_SIP_PASS:-sippass}
    ports:
      - "9001:9001"
    depends_on:
      - mycel-db

  scheduler:
    build: .
    volumes:
      - .:/app
      - logs-data:/app/logs
      - bundler-data:/usr/local/bundle
    command: cron -f -l 2

  mycel-db:
    image: mysql:5.5
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYCEL_PASSWORD:-secret}
      MYSQL_DATABASE: mycel
      MYSQL_USER: ${MYCEL_USERNAME:-mycel}
      MYSQL_PASSWORD: ${MYCEL_PASSWORD:-secret}
    volumes:
      - db-data:/var/lib/mysql

