source "http://rubygems.org"
gem "activerecord"
gem "sqlite3"
gem "goliath"
gem "em-synchrony"
gem "mysql2"
gem "slim"
gem "grape"
gem "rake"

group :development do
  gem "pry"
  gem "awesome_print"
  gem "rails-erd"
end

group :test do
  gem "clean_test", :require => false
  gem "rack-test", :require => false
end
