source "http://rubygems.org"
gem "activerecord"
gem "sqlite3"
gem "goliath"
gem "em-synchrony"
gem "mysql2"
gem "slim"
gem "grape"
gem "clean_test", :require => false
gem "rack-test", :require => false
