require "rake/testtask"
require "em-synchrony/activerecord"
require "./models"

task :default => [:test]

Rake::TestTask.new do |test|
  test.libs << "test"
  test.test_files = Dir[ "test/test_*.rb" ]
  test.verbose = true
end

namespace :db do
  desc 'Build tables and seed MySQL for development'
  task :seed do
    dbconfig = YAML::load(File.open("config/database.yml"))
    ActiveRecord::Base.establish_connection(dbconfig["development"])

    load "db/schema.rb"

    seed = YAML::load(File.open("db/seed.yml"))
    org = Organization.create(:name => seed['organization'])

    seed['branches'].each do |branch|
      b = Branch.create(:name => branch['name'])
      org.branches << b
      branch['departments'].each do |department|
        d = Department.create(:name => department['name'])
        b.departments << d
        department['clients'].each do |client|
          short = client['shorttime'] ||= 0
          c = Client.new(:name => client['name'], :ipaddr => client['IPaddr'],
                         :hwaddr => client['HWaddr'], :shorttime => short)
          d.clients << c
        end
      end
    end

    seed['screenres'].each { |res| ScreenResolution.create(:resolution => res) }

  end
end

# se ellers:
# https://github.com/rails/rails/blob/master/activerecord/Rakefile
# for inspirasjon