require "rake/testtask"


task :default => [:test]

Rake::TestTask.new do |test|
  test.libs << "test"
  test.test_files = Dir[ "test/test_*.rb" ]
  test.verbose = true
end

# TODO, db:setup stuff
namespace :db do
  desc 'Build the MySQL database'
  task :build do
    puts "building"     
  end

  desc "drop the tables"
  task :drop do
    puts "dropping"
  end
end

#require 'yaml'

# desc "Migrate the database through scripts in db/migrate. Target specific version with VERSION=x"
# task :migrate => :environment do
#   ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil )
# end

# task :environment do
#   ActiveRecord::Base.establish_connection(YAML::load(File.open('database.yml')))
#   ActiveRecord::Base.logger = Logger.new(File.open('database.log', 'a'))
# end

# se ellers:
# https://github.com/rails/rails/blob/master/activerecord/Rakefile
# for inspirasjon